basic_info:
    created_by: 
        - Ryan
        - Ying
        - Henry
    date: 2018
file_path:
    skills_dict: files/key_skill.csv
    path_to_resume: files/resume_ryan_kang.docx
    path_to_jobs: files/ds.csv


