basic_info:
    created_by: 
        - Ryan
        - Ying
        - Henry
    date: 2018
file_path:
    skills_dict: NLP/key_skill.csv
    resume_uploaded: resume_file/resume_ryan_kang.docx
    use_anonymous: yes
